### ISSUE TITLE
I got some error when I try the script

### ISSUE THREAD

**Issue by engmsaleh** [harsh4870/ECR-Token-automation#2]
I have got some issues when trying the script, but this what eventually worked
```
TOKEN=`aws ecr --region=$REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 --decode | cut -d: -f2
```

**Comment by harsh4870** [comment]
@engmsaleh  Can you please share error if there is any.

**Comment by engmsaleh** [comment]
@harsh4870 I think there were two issues that I have faced
- First the single quote `'authorizationData[].authorizationToken'` I have added it as without it it gave an error that it doesn't recognize `authorizationData[].authorizationToken`

- The second issue was `base64 -d` it gave unknown flag

**Comment by harsh4870** [comment]
@engmsaleh whichh os platform you are using ?

**Comment by engmsaleh** [comment]
I'm using mac osx

**Comment by harsh4870** [comment]
@engmsaleh  it's working well on my ubuntu system.

**Comment by harsh4870** [comment]
@engmsaleh  any update ?

**Comment by engmsaleh** [comment]
I think I have modified the script and what worked for me is the following

```
TOKEN=`aws ecr --region=$REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -di | cut -d: -f2`
```
